# Generated by Django 2.1.7 on 2019-03-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
